name: Build
on: [push]

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: wonderlandengine/editor:latest
    steps:
    - name: Install
      run: yes | apt-get install git git-lfs
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Package
      run: |
        mkdir public
        # Build @wonderlandengine/react-ui package
        npm ci
        npm run build
        # Build example project
        /usr/local/bin/entrypoint.sh WonderlandEditor --windowless --package --project example/ReactUi.wlp --output ./public/
      env:
          WLE_CREDENTIALS: ${{ secrets.WLE_CREDENTIALS }}
    - name: Gzip
      run: gzip -k public/**/*.*
    - name: Upload package artifact
      uses: actions/upload-artifact@v2
      with:
        name: wonderland-engine-examples-deploy
        path: public/
  deploy-pages:
    needs: package
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download package artifact
      uses: actions/download-artifact@v2
      with:
        name: wonderland-engine-examples-deploy
        path: public/
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: public
